FROM ubuntu
# RUN sudo su
RUN apt-get update
RUN apt-get install net-tools
RUN apt-get install sudo
RUN pip3 install --upgrade pip 
RUN pip3 install djangorestframework
# WORKDIR /var/FutuOpenD_5.4.1608_Ubuntu16.04/FutuOpenD_5.4.1608_Ubuntu16.04
# RUN ls
# RUN ./FutuOpenD
# ENTRYPOINT ["input_phone_verify_code -code="]
# CMD sleep infinity