version: '3'

services:
    db:
        image: timescale/timescaledb:latest-pg12
        volumes:
            - /Beatthemarket/data/db:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
    web:
        build: ./Beatthemarket
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./Beatthemarket:/code
            - ./software:/var
        ports:
            - "8000:8000"
        depends_on:
            - db
    frontend:
        build: ./btm_frontend
        command: ["npm", "start"]
        # command: ["npm", "run build"]
        volumes:
            - ./btm_frontend:/var/app/btm_frontend
            - ./btm_frontend/node_modules:/var/app/btm_frontend/node_modules
        environment:
            CHOKIDAR_USEPOLLING: "true"
        ports:
            - "3000:3000"
        tty: true
        stdin_open: true
    redis:
        image: redis
        restart: unless-stopped
        volumes: 
            - ./tmp:/data 
        expose:
            - "6379"

volumes:
    Software:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: C:\Users\Jason.DESKTOP-FORTAGF\Documents\GitHub\Warrant\software