# Generated by Django 3.1.7 on 2021-10-12 16:52

from django.db import migrations, models
import django.db.models.deletion
import timescale.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hk_stock',
            fields=[
                ('code', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('include_warrant', models.BooleanField(default=True)),
                ('include_call', models.IntegerField(blank=True, default=None, null=True)),
                ('include_put', models.IntegerField(blank=True, default=None, null=True)),
                ('include_bull', models.IntegerField(blank=True, default=None, null=True)),
                ('include_bear', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='hk_warrant',
            fields=[
                ('code', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=63, null=True)),
                ('wrt_status', models.CharField(max_length=31, null=True)),
                ('wrt_strike_price', models.FloatField(null=True)),
                ('wrt_conversion_ratio', models.FloatField(null=True)),
                ('wrt_type', models.CharField(max_length=7, null=True)),
                ('wrt_issuer_code', models.CharField(max_length=7, null=True)),
                ('listing_date', models.DateField(null=True)),
                ('wrt_maturity_date', models.DateField(null=True)),
                ('wrt_end_trade', models.DateField(null=True)),
                ('stock_owner', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='warrant.hk_stock')),
            ],
        ),
        migrations.CreateModel(
            name='warrant_recommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_dict', models.JSONField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='warrant_setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settings', models.JSONField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='warrant_market_closed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=7)),
                ('update_timestamp', models.DateField()),
                ('name', models.CharField(max_length=63)),
                ('last_price', models.FloatField(null=True)),
                ('open_price', models.FloatField(null=True)),
                ('high_price', models.FloatField(null=True)),
                ('low_price', models.FloatField(null=True)),
                ('prev_close_price', models.FloatField(null=True)),
                ('price_spread', models.FloatField(null=True)),
                ('wrt_strike_price', models.FloatField(null=True)),
                ('wrt_break_even_point', models.FloatField(null=True)),
                ('wrt_conversion_price', models.FloatField(null=True)),
                ('volume', models.PositiveBigIntegerField(null=True)),
                ('wrt_street_vol', models.PositiveBigIntegerField(null=True)),
                ('wrt_issue_vol', models.PositiveBigIntegerField(null=True)),
                ('wrt_street_ratio', models.FloatField(null=True)),
                ('listing_date', models.DateField(null=True)),
                ('wrt_maturity_date', models.DateField(null=True)),
                ('wrt_end_trade', models.DateField(null=True)),
                ('wrt_status', models.CharField(max_length=31, null=True)),
                ('wrt_conversion_ratio', models.FloatField(null=True)),
                ('wrt_type', models.CharField(max_length=7, null=True)),
                ('wrt_issuer_code', models.CharField(max_length=7, null=True)),
                ('wrt_delta', models.FloatField(null=True)),
                ('wrt_implied_volatility', models.FloatField(null=True)),
                ('wrt_premium', models.FloatField(null=True)),
                ('wrt_leverage', models.FloatField(null=True)),
                ('wrt_ipop', models.FloatField(null=True)),
                ('wrt_score', models.FloatField(null=True)),
                ('wrt_transaction', models.JSONField(blank=True, default=None, null=True)),
                ('stock_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warrant.hk_stock')),
            ],
            options={
                'db_table': 'warrant_market_closed',
            },
        ),
        migrations.CreateModel(
            name='hk_warrant_timescale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 min')),
                ('update_time', models.DateField(null=True)),
                ('bid_price', models.FloatField(default=None, null=True)),
                ('ask_price', models.FloatField(default=None, null=True)),
                ('bid_vol', models.FloatField(default=None, null=True)),
                ('ask_vol', models.FloatField(default=None, null=True)),
                ('price_spread', models.FloatField(default=None, null=True)),
                ('wrt_sensitivity', models.FloatField(default=None, null=True)),
                ('stock_bid_price', models.FloatField(default=None, null=True)),
                ('stock_ask_price', models.FloatField(default=None, null=True)),
                ('stock_bid_vol', models.FloatField(default=None, null=True)),
                ('stock_ask_vol', models.FloatField(default=None, null=True)),
                ('stock_price_spread', models.FloatField(default=None, null=True)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warrant.hk_warrant')),
                ('stock_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warrant.hk_stock')),
            ],
        ),
        migrations.CreateModel(
            name='hk_stock_timescale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 min')),
                ('last_price', models.FloatField(null=True)),
                ('open_price', models.FloatField(null=True)),
                ('high_price', models.FloatField(null=True)),
                ('low_price', models.FloatField(null=True)),
                ('price_spread', models.FloatField(null=True)),
                ('volume', models.PositiveBigIntegerField(null=True)),
                ('turnover', models.PositiveBigIntegerField(null=True)),
                ('turnover_rate', models.FloatField(null=True)),
                ('amplitude', models.FloatField(null=True)),
                ('technical_analysis', models.JSONField(blank=True, default=None, null=True)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warrant.hk_stock')),
            ],
        ),
    ]
