# Generated by Django 3.1.7 on 2021-06-14 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hk_stock',
            fields=[
                ('code', models.CharField(max_length=7, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='warrant_market_closed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=7)),
                ('update_timestamp', models.DateField()),
                ('name', models.CharField(max_length=63)),
                ('last_price', models.FloatField(null=True)),
                ('open_price', models.FloatField(null=True)),
                ('high_price', models.FloatField(null=True)),
                ('low_price', models.FloatField(null=True)),
                ('prev_close_price', models.FloatField(null=True)),
                ('price_spread', models.FloatField(null=True)),
                ('wrt_strike_price', models.FloatField(null=True)),
                ('wrt_break_even_point', models.FloatField(null=True)),
                ('wrt_conversion_price', models.FloatField(null=True)),
                ('volume', models.PositiveBigIntegerField(null=True)),
                ('wrt_street_vol', models.PositiveBigIntegerField(null=True)),
                ('wrt_issue_vol', models.PositiveBigIntegerField(null=True)),
                ('wrt_street_ratio', models.FloatField(null=True)),
                ('listing_date', models.DateField(null=True)),
                ('wrt_maturity_date', models.DateField(null=True)),
                ('wrt_end_trade', models.DateField(null=True)),
                ('wrt_status', models.CharField(max_length=31, null=True)),
                ('wrt_conversion_ratio', models.FloatField(null=True)),
                ('wrt_type', models.CharField(max_length=7, null=True)),
                ('wrt_issuer_code', models.CharField(max_length=7, null=True)),
                ('wrt_delta', models.FloatField(null=True)),
                ('wrt_implied_volatility', models.FloatField(null=True)),
                ('wrt_premium', models.FloatField(null=True)),
                ('wrt_leverage', models.FloatField(null=True)),
                ('wrt_ipop', models.FloatField(null=True)),
                ('wrt_score', models.FloatField(null=True)),
                ('stock_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warrant.hk_stock')),
            ],
            options={
                'db_table': 'warrant_market_closed',
            },
        ),
        migrations.CreateModel(
            name='warrant_transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_timestamp', models.DateField(auto_now=True)),
                ('transaction', models.JSONField()),
                ('code', models.ManyToManyField(to='warrant.warrant_market_closed')),
            ],
            options={
                'db_table': 'warrant_transaction',
            },
        ),
    ]
