# Generated by Django 3.1.7 on 2021-06-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrant', '0002_auto_20210616_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='warrant_market_closed',
            name='warrant_transaction',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.DeleteModel(
            name='warrant_transaction',
        ),
    ]
