# Generated by Django 3.1.7 on 2021-06-16 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warrant', '0003_auto_20210616_1329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warrant_market_closed',
            old_name='warrant_transaction',
            new_name='wrt_transaction',
        ),
    ]
