# Generated by Django 3.1.7 on 2021-06-19 16:58

from django.db import migrations, models
import django.db.models.deletion
import timescale.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('warrant', '0004_auto_20210616_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='hk_stock_timescale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='3 min')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warrant.hk_stock')),
            ],
        ),
    ]
