# Generated by Django 3.1.7 on 2021-06-21 15:31

from django.db import migrations, models
import timescale.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('warrant', '0005_hk_stock_timescale'),
    ]

    operations = [
        migrations.CreateModel(
            name='warrant_settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settings', models.CharField(max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='hk_stock_timescale',
            name='amplitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='hk_stock_timescale',
            name='high_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='hk_stock_timescale',
            name='last_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='hk_stock_timescale',
            name='low_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='hk_stock_timescale',
            name='open_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='hk_stock_timescale',
            name='price_spread',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='hk_stock_timescale',
            name='turnover',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='hk_stock_timescale',
            name='turnover_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='hk_stock_timescale',
            name='volume',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hk_stock_timescale',
            name='time',
            field=timescale.db.models.fields.TimescaleDateTimeField(interval='1 min'),
        ),
    ]
