# Generated by Django 3.1.7 on 2021-07-31 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrant', '0006_auto_20210621_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='warrant_recommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_dict', models.CharField(max_length=5011)),
            ],
        ),
        migrations.AddField(
            model_name='warrant_settings',
            name='settings_status',
            field=models.BooleanField(default=False),
        ),
    ]
