# Generated by Django 3.1.7 on 2021-07-31 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warrant', '0008_auto_20210731_1812'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='warrant_settings',
            new_name='warrant_setting',
        ),
    ]
