# Generated by Django 3.1.7 on 2021-08-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrant', '0009_auto_20210731_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='hk_stock',
            name='include_warrant',
            field=models.BooleanField(default=True),
        ),
    ]
