# Generated by Django 3.1.7 on 2021-08-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrant', '0010_hk_stock_include_warrant'),
    ]

    operations = [
        migrations.AddField(
            model_name='hk_stock_timescale',
            name='technical_analysis',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
