# Generated by Django 3.1.7 on 2021-08-22 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warrant', '0012_auto_20210823_0029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hk_stock',
            name='include_bear',
        ),
        migrations.RemoveField(
            model_name='hk_stock',
            name='include_bull',
        ),
        migrations.RemoveField(
            model_name='hk_stock',
            name='include_call',
        ),
        migrations.RemoveField(
            model_name='hk_stock',
            name='include_put',
        ),
    ]
