# Generated by Django 3.1.7 on 2021-08-22 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warrant', '0013_auto_20210823_0104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hk_warrant_timescale',
            name='code',
        ),
        migrations.RemoveField(
            model_name='hk_warrant_timescale',
            name='stock_owner',
        ),
        migrations.DeleteModel(
            name='hk_warrant',
        ),
        migrations.DeleteModel(
            name='hk_warrant_timescale',
        ),
    ]
