# Generated by Django 3.1.7 on 2021-08-23 08:05

from django.db import migrations, models
import django.db.models.deletion
import timescale.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('warrant', '0014_auto_20210823_0105'),
    ]

    operations = [
        migrations.CreateModel(
            name='hk_warrant',
            fields=[
                ('code', models.CharField(max_length=7, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='hk_stock',
            name='include_bear',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='hk_stock',
            name='include_bull',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='hk_stock',
            name='include_call',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='hk_stock',
            name='include_put',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.CreateModel(
            name='hk_warrant_timescale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 min')),
                ('ask_price', models.FloatField(default=None, null=True)),
                ('bid_price', models.FloatField(default=None, null=True)),
                ('ask_vol', models.FloatField(default=None, null=True)),
                ('bid_vol', models.FloatField(default=None, null=True)),
                ('stock_ask_price', models.FloatField(default=None, null=True)),
                ('stock_bid_price', models.FloatField(default=None, null=True)),
                ('stock_ask_vol', models.FloatField(default=None, null=True)),
                ('stock_bid_vol', models.FloatField(default=None, null=True)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warrant.hk_warrant')),
                ('stock_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warrant.hk_stock')),
            ],
        ),
    ]
