# Generated by Django 3.1.7 on 2021-08-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrant', '0015_auto_20210823_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warrant_setting',
            name='settings_status',
        ),
        migrations.AlterField(
            model_name='warrant_setting',
            name='settings',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
