# Generated by Django 3.1.7 on 2021-08-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrant', '0016_auto_20210823_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='hk_warrant_timescale',
            name='price_spread',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='hk_warrant_timescale',
            name='stock_price_spread',
            field=models.FloatField(default=None, null=True),
        ),
    ]
