# Generated by Django 3.1.7 on 2021-09-01 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrant', '0017_auto_20210831_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='hk_warrant_timescale',
            name='wrt_sensitivity',
            field=models.FloatField(default=None, null=True),
        ),
    ]
