# Generated by Django 3.1.7 on 2021-09-01 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrant', '0018_hk_warrant_timescale_wrt_sensitivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hk_stock',
            name='include_bear',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='hk_stock',
            name='include_bull',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='hk_stock',
            name='include_call',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='hk_stock',
            name='include_put',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
