# Generated by Django 3.1.7 on 2021-09-13 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warrant', '0019_auto_20210901_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='hk_warrant',
            name='listing_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='hk_warrant',
            name='name',
            field=models.CharField(default=None, max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='hk_warrant',
            name='stock_owner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='warrant.hk_stock'),
        ),
        migrations.AddField(
            model_name='hk_warrant',
            name='wrt_conversion_ratio',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='hk_warrant',
            name='wrt_end_trade',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='hk_warrant',
            name='wrt_issuer_code',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='hk_warrant',
            name='wrt_maturity_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='hk_warrant',
            name='wrt_status',
            field=models.CharField(max_length=31, null=True),
        ),
        migrations.AddField(
            model_name='hk_warrant',
            name='wrt_type',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='hk_warrant_timescale',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warrant.hk_warrant'),
        ),
        migrations.AlterField(
            model_name='hk_warrant_timescale',
            name='stock_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warrant.hk_stock'),
        ),
        migrations.AlterField(
            model_name='warrant_market_closed',
            name='stock_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warrant.hk_stock'),
        ),
    ]
