# Generated by Django 3.1.7 on 2021-09-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrant', '0020_auto_20210913_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='hk_warrant',
            name='wrt_strike_price',
            field=models.FloatField(null=True),
        ),
    ]
