# Generated by Django 3.1.7 on 2021-09-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrant', '0021_hk_warrant_wrt_strike_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='hk_warrant_timescale',
            name='update_time',
            field=models.DateField(null=True),
        ),
    ]
